### List all messages
GET http://localhost:3000/messages/students
content-type: application/json

### Create New message
POST http://localhost:3000/messages/new
content-type: application/json

{
    "content" : "new messages"
}

### Get a particular message
GET http://localhost:3000/messages/951


##################################################################

# ### Get all students
# GET http://localhost:3000/students/get

# ### Post new student
# POST http://localhost:3000/students/new
# content-type: application/json

# {
#     "content" : 98,
#     "school" : "Boss"

# }
